{{- if .Values.backend.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-backend-secrets
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.backend.secrets.secretKey }}
  secret_key: {{ .Values.backend.secrets.secretKey | b64enc | quote }}
  {{- else }}
  secret_key: {{ randAlphaNum 50 | b64enc | quote }}
  {{- end }}
{{- end }}